# Analyze before publish: flutter pub publish --dry-run
# Publish: flutter pub publish
name: remote_config_feature_manager
description: Firebase Remote Config feature manager for developer preferences, experiments, A/B tests etc.
version: 3.0.4
repository: https://github.com/theRealGetman/remote-config-feature-manager
issue_tracker: https://github.com/theRealGetman/remote-config-feature-manager/issues

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  feature_manager: ">=3.0.4 <4.0.0"
  shared_preferences: ">=2.1.2 <3.0.0"
  firebase_remote_config: ">=5.0.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
